nome = str(input('Digite o seu nome completo: ')).strip()
print('Seu nome em maiúsculas é', nome.upper())
print('Seu nome em minúsculas é', nome.lower())
espaco = nome.replace(' ', '')
letras = len(espaco.strip())
print('Seu nome completo tem {} letras'.format(letras))
primeiro = nome.split()
print('Primeiro nome {} e tem {} letras.'.format(primeiro[0], len(primeiro[0][0:])))
