a = input('Digite algo: ')
print('O tipo primitivo desse valor é', type(a))
print('É númerico?', a.isnumeric())
print('É alfanúmerico?', a.isalnum())
print('É alfabético?', a.isalpha())
print('Esta em maiusculas?', a.isupper())
print('Esta em minusculas?', a.islower())
print('Esta Capitalizada?', a.istitle())
print('Só tem espaço?', a.isspace())
